### ISSUE TITLE
Check in lock files for all apps

### ISSUE THREAD

**Issue by tombruijn** [appsignal/test-setups#110]
Let's check in the lock files. I just had the issue where the rails 6 sidekiq app didn't work locally but it did on the test setups CI works.

Locally the pg gem wouldn't install and when that was fixed there was a mail gem issue. On CI it installed the latest version of gems because it has no gemfile, but locally it used an older version from the first time I installed the app. The repo would be more stable and easier to reproduce if we're all using the same versions of dependencies.

Lock files: Gemfile.lock, package-lock.json, mix.lock

## To do

- [x] Remove all lock files from the gitignore file
- [x] Check in lock files for all apps

**Comment by tombruijn** [comment]
@thijsc can you leave your thoughts, if you have any others than in this Slack convo: https://appsignal.slack.com/archives/CNPP953E2/p1683185552052869

**Comment by thijsc** [comment]
The way I use the test setups is to constantly run `rake clean` to get a clean current state. I think it's important to try and reproduce things with whatever the current versions that match the version specifiers are.

If we were to freeze that state we introduce a couple of problems. With outdated dependencies the whole thing might not run, you'd have to update anyway. Also customers are likely to use newer versions, so by freezing in time we are not getting any closer to reality.

We could add lock files and run Depfu. I don't see the point though: By simply nuking the lockfile constantly we get the same result with much less overhead. I agree that we should all use the same dependencies, but I think the method should be to start with a clean lockfile basically daily.

**Comment by tombruijn** [comment]
> I think it's important to try and reproduce things with whatever the current versions that match the version specifiers are.

It's more important to reproduce it with the versions users report to us it's broken with, if we use it for support purposes. That's more of than not, not the most recent version. We can down- and up-grade if needed, and lock it on the most recent version when done.

The first thing one should do when using this repo to reproduce an issue, is lock the packages to the versions the user in support is using, that can be lower or higher.

Upgrades of package can be more than a version bump. They drop support for older methods or introduce new ways of configuring ways and keeping the old ways around only for legacy purposes. Semver? Yes, but no. Just like we don't follow semver.

> We could add lock files and run Depfu. I don't see the point though: By simply nuking the lockfile constantly we get the same result with much less overhead. I agree that we should all use the same dependencies, but I think the method should be to start with a clean lockfile basically daily.

_Upgrades require attention_. That's why we don't let depfu/dependabot commit directly on the main branches either. It's better to know an upgrade breaks things _before merging_ it, than waking one morning and seeing the CI is broken, again.

> With outdated dependencies the whole thing might not run, you'd have to update anyway.

With every version being locked: the docker file, the lock files of the app, etc. things should not break. That's their whole purpose.

If we throw away lock files these apps break for reasons we shouldn't care about, like dependency resolving going wrong. Package managers still trip on language version locks and I don't want to have to deal with that whenever a package drops support for an old Ruby or Node.js version. The CI will remain as unstable as it is now and no one will care about it, because it keeps breaking.

> Also customers are likely to use newer versions, so by freezing in time we are not getting any closer to reality.

See my [earlier points](https://appsignal.slack.com/archives/CNPP953E2/p1683200355175999?thread_ts=1683185552.052869&cid=CNPP953E2) on using this repo for integration tests for the latest releases of packages we integrate with: we shouldn't. You're continuously causing issues for apps using the latest versions of things, even if we never have to use them.
