### ISSUE TITLE
Node test examples fail to start when agent is already built from host machine

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/test-setups#26]
If you run one of the Node examples and the integration's agent extension has been already built from the host machine, which doesn't have the same architecture as the Docker container, you'll see this when the example application starts.

```
app_1       | node: AppSignal extension not loaded. This could mean that your current environment isn't supported, or that another error has occurred.
```
What this actually means is: `invalid ELF header`

**Comment by tombruijn** [comment]
We could run `mono clean` for Node.js apps. That should clean up any build artifacts of the agent and extension.

But I think we shouldn't be in the situation you run the app on the host machine, only to test something specifically for macOS. If the test apps setup itself is broken we should prioritize fixing that.
