### ISSUE TITLE
Tests aren't passing due to an error building Processmon

### ISSUE THREAD

**Issue by unflxw** [appsignal/test-setups#65]
Sample Semaphore issue: https://appsignal.semaphoreci.com/jobs/d09caa93-e109-4279-94c8-6a6340444bb9

**Comment by tombruijn** [comment]
Looks like processmon deps need stricter version locks. This will probably have broken in the repo as well if you do a fresh clone.

Caching the processmon executable between builds can help fix/hide this for some time, and also speed up the build, because we don't need to build it for every test.
