### ISSUE TITLE
Add logging API usage examples

### ISSUE THREAD

**Issue by unflxw** [appsignal/test-setups#93]
Recently, @shairyar [modified the Oban test app so that it uses the logging beta API](https://github.com/appsignal/test-setups/commit/e08c561722adbe1fa462ddeab3bc9c12dbca618a). This is a great idea, and we should do more of it!

## To do

- [x] Have a Rails test setup [use the Ruby logger as the Rails logger]
- [x] Have a Rails test setup [use the Ruby logger with Lograge
](https://docs.appsignal.com/logging/platforms/integrations/ruby.html#lograge) https://github.com/appsignal/test-setups/pull/108
- [x] Have a Node.js application use a [Winston logger] https://github.com/appsignal/test-setups/pull/108(https://docs.appsignal.com/logging/platforms/integrations/nodejs.html#usage-with-winston)
- [x] Have test setups use the logging API directly
    - [x] Elixir (done in the Oban test setup; thanks @shairyar!)
    - [x] Ruby
    - [x] Node.js
- [x] When implemented, have a Phoenix test setup use the [Elixir logging backend](https://github.com/appsignal/appsignal-elixir/issues/800)
- [x] When/if implemented, have a Node.js test setup use a [Pino logger](https://github.com/appsignal/appsignal-nodejs/issues/828)

**Comment by unflxw** [comment]
The Rails 7 + Sidekiq test setup already [configures the logger for the Sidekiq workers](https://github.com/appsignal/test-setups/blob/main/ruby/rails7-sidekiq/app/config/initializers/sidekiq.rb#L2), so that's quite neat as well.

**Comment by tombruijn** [comment]
We don't see the logs in the terminal for Rails sidekiq app at the moment, which I would prefer. Let's look if we can also send the logs to the terminal.
